url: "https://www.sanidepanne.fr" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Sani Dépanne" # the name of your site, e.g. ACME Corp.

global_variables:
  formspree_url: "https://formspree.io/f/mdkovwga"

collections:
  pages:
    output: true

include:
  - "robots.txt"
  - "sitemap.xml"
  - ".htaccess"
